# Generated by Django 4.2.16 on 2024-11-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO app_applications (name, is_visible) 
                VALUES
                    ('ELD Rider', true),
                    ('XELD', true),
                    ('Optima ELD', true),
                    ('Pro Ride ELD', true),
                    ('Sparkle ELD', true),
                    ('Xplore ELD', true),
                    ('PTI ELD', true),
                    ('TX ELD', true),
                    ('EVA ELD', true),
                    ('RouteMate ELD', true),
                    ('Apex ELD', true),
                    ('Rock ELD', true);
                """
        ),

        migrations.RunSQL(
            sql="""
                INSERT INTO app_eldcommands(is_visible, command, description) VALUES
                    (true, 'SHIPMODE', 'Fully power down device, clears engine data information and makes detection process start again'),
                    (true, 'RECAST', 'Pushing config on Cast.'),
                    (true, 'SETPARAMS 998=0;', 'Turns off beeping noise on ELD'),
                    (true, 'DIAG CAN', 'Returns data on the device canbus status'),
                    (true, 'DIAG ELD', 'Minimum conformity of found engine data for ELD usage'),
                    (true, 'DIAG DISC', 'Retrieves ECU data discovered'),
                    (true, 'DIAG VERSION', 'Returns information on the device version'),
                    (true, 'DIAG CONFIG', 'Retrieves information about the current configuration of a device'),
                    (true, 'DIAG DEVICEINFO', 'Retrieves information about the device BLE'),
                    (true, 'DIAG QUEUE', 'Returns information about the device packet queue'),
                    (true, 'SETPARAMS 527=0;', 'Kills the devices OBD readings'),
                    (true, 'SETPARAMS 527=1;', 'Basic OBD readings'),
                    (true, 'SETPARAMS 527=2;', 'Reading over OBD J1939'),
                    (true, 'SETPARAMS 527=3;', 'Reading mixed J1939 and J1708'),
                    (true, 'SETPARAMS 527=4;', 'Reading over OBD J1708'),
                    (true, 'SETPARAMS 527=5;', 'Auto detecting OBD protocol'),
                    (true, 'SETPARAMS 527=6;', 'Use only for 87A devices with special harness on Paccar engines'),
                    (true, 'BLETEST 2', '87A, 88A, 87U, 88U - Resets bluetooth'),
                    (true, 'BLETEST 9', '87A, 88A, 87U, 88U - Reprogram bluetooth - only use if bluetooth reset is not working'),
                    (true, 'BLETEST 34', '87B, 88B - Resets bluetooth'),
                    (true, 'SETPARAMS 542=1;', 'Potential fix for 65535 Bluetooth version');
                """
        ),

        migrations.RunSQL(
            sql="""
              INSERT INTO app_skyonics(name, is_visible) VALUES
                  ('Lioneight', true),
                  ('Darex', true),
                  ('Optima', true);
              """
        ),
    ]
