# Generated by Django 4.2.16 on 2024-11-30 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial_inserts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunctionlettershistory',
            name='codriver_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctionlettershistory',
            name='expires_at',
            field=models.DateField(default=datetime.date(2024, 12, 8)),
        ),
    ]
