# Generated by Django 4.2.16 on 2024-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_malfunctionlettershistory_codriver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunctionlettershistory',
            name='expires_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
