# Generated by Django 4.2.16 on 2024-11-20 11:37

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import app.models
import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to=app.models.get_app_logo)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),

        migrations.CreateModel(
            name='EldCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),

        migrations.CreateModel(
            name='Skyonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),

        migrations.CreateModel(
            name='MalfunctionLettersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('vehicle_name', models.CharField(max_length=64)),
                ('serial_number', models.CharField(max_length=16)),
                ('driver_name', models.CharField(max_length=64)),
                ('codriver_name', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField(default=datetime.date(2024, 11, 28))),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.applications')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EldCommandsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eldcommands')),
                ('skyonics_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skyonics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
